# Generated by Django 4.2.30 on 2026-04-25 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, default='')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='books_title_7a737c_idx'), models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['genre'], name='books_genre_d6e4af_idx')],
            },
        ),
    ]
